---

name: test build

on: push

jobs:
  generate-markdown:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: "Process datafiles"
        container:
          image: fzipi/owasp-samm-preprocess-yaml:0.1
          volumes:
            - Datafiles:/build/Datafiles
            - output:/build/output
        args: /build/output

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v1
        with:
          name: markdown-files
          path: output
        
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v1

    - name: Download markdown-files
      with:
        name: markdown-files
      run: |
        mkdir -p business-function/practice/stream
        sed -i -e 's:- False:- "No":g' *.md
        mv Design.md Governance.md Implementation.md Operations.md Verification.md business-function
        mv *-??-?.md business-function/practice/stream
        mv *.md business-function/practice
