---

name: test build

on: push

jobs:
  generate-markdown:
    runs-on: ubuntu-18.04
    # volumes:
    #    - Datafiles:/build/Datafiles
    #    - output:/build/output
    #  args: /build/output
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output

      - name: "Process datafiles"
        uses: docker://fzipi/owasp-samm-preprocess-yaml:version-0.3.5
        with: # needs a README in your repo root!
          args: "-d Datafiles -o output"

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v1
        with:
          name: markdown-files
          path: output/markdown
        
  build:
    runs-on: ubuntu-18.04
    needs: generate-markdown
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v1
      name: Download markdown-files
      with:
        name: markdown-files

    - name: "Process artifacts"
      run: |
        cd output/markdown
        mkdir -p business-function/practice/stream
        sed -i -e 's:- False:- "No":g' \*.md
        mv Design.md Governance.md Implementation.md Operations.md Verification.md business-function
        mv \*-??-?.md business-function/practice/stream
        mv \*.md business-function/practice
        
